apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authservice-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UDLAIA-STATS/authservice.git
    targetRevision: develop
    path: develop
  destination:
    server: https://kubernetes.default.svc
    namespace: authservice-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
