name: Django CI/CD

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

env:
  DEBUG: True
  DB_ENGINE: django.db.backends.postgresql
  ALLOWED_HOSTS: localhost,127.0.0.1
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5440
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Configurar entorno Django
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Pull docker repository
        run: |
          docker pull dase123/udlaia-stats:udla_postgres
      
      - name : Run docker container
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          docker run -d \
            -p 5440:5432 \
            --name udla_postgres \
            -e POSTGRES_DB=$POSTGRES_DB \
            -e POSTGRES_USER=$POSTGRES_USER \
            -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            dase123/udlaia-stats:udla_postgres

      - name: Wait for PostgreSQL to be ready
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
          echo "⏳ Esperando que PostgreSQL esté listo..."
          for i in {1..20}; do
            if docker exec udla_postgres pg_isready -U $POSTGRES_USER -d $POSTGRES_DB > /dev/null 2>&1; then
              echo "✅ PostgreSQL está disponible!"
              break
            fi
            echo "Esperando... intento $i/20"
            sleep 3
          done

          docker ps
          echo "Verificando logs del contenedor..."
          docker logs udla_postgres | tail -n 20

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install django djangorestframework pytest pytest-django psycopg2-binary    
      - name: Run migrations
        env:
          DJANGO_SETTINGS_MODULE: authservice.settings
        run: |
          python manage.py migrate --noinput

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: authservice.settings
        run: |
          pytest -v --maxfail=1 --disable-warnings
