name: Django CI/CD

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Ejecutar pruebas Django

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install django djangorestframework pytest pytest-django

      - name: Check Django environment
        env:
          DJANGO_SETTINGS_MODULE: authservice.settings
        run: |
          python manage.py check
          python manage.py migrate --noinput

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: authservice.settings
        run: |
          pytest -v --maxfail=1 --disable-warnings
  create-pr-main:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()  
    steps:
      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PR_TOKEN }}
          branch: develop
          base: main
          title: "Auto PR: Merge develop into main"
          labels: automated-pr
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            Este Pull Request fue generado autom√°ticamente luego de pasar las pruebas en Django.
