name: Deploy AuthService to DockerHub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_NAME: udlaia-stats
      SERVICE_NAME: authservice

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python environmente
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      -  run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Django health check
        run: |
          python manage.py check
          python manage.py migrate --noinput
          echo "AuthService health check passed"

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: authservice.settings
        run: |
          pytest -v --maxfail=1 --disable-warnings

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SERVICE_NAME }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SERVICE_NAME }}-${{ github.run_number }}

      # 7️⃣ Confirmación
      - name: Deployment summary
        run: |
          echo "✅ AuthService deployed successfully!"
          echo "Image: ${{ vars.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.SERVICE_NAME }}"
